# Generated by Django 3.0.7 on 2020-06-24 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='descreption_job',
            field=models.TextField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
