# Generated by Django 3.0.7 on 2020-06-24 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_job_descreption_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='experiance_job',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='job',
            name='published_job',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='job',
            name='salary_job',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='vacancy_job',
            field=models.IntegerField(default=1),
        ),
    ]
